---
title: "Design Philosophy"
format:
  html:
    toc: true
vignette: >
  %\VignetteIndexEntry{Design Philosophy}
  %\VignetteEngine{quarto::html}
  %\VignetteEncoding{UTF-8}
---

This package provides a set of tools to manage reproducible analysis workflows that use Quarto.
The goal is to provide the "simplest way that works".
That said, this package has two main ideas:

1.  A "workflow" is a sequence of `.qmd` files.
    Each file writes to its own data directory and can read from earlier steps.

2.  Package dependencies are managed using a DESCRIPTION file.

These two ideas are independent of each other.

There are more-comprehensive tools that address each of these ideas, for example: [renv](https://rstudio.github.io/renv/index.html) for package dependencies, and [targets](https://docs.ropensci.org/targets/) for workflow dependencies.
This package does *not* aspire to compete with these approaches.
Rather, it aspires to be a lightweight first step towards these more-comprehensive approaches, as your needs may dictate.

## Main ideas

### Sequence of Quarto files

This package proposes a concept of a *workflow*: an overloaded word, to be sure.
Here, a workflow consists of a directory containing a sequence of `.qmd` files and a data directory.
An example:

    analyses/
      data/
        00-import/
        01-do-stuff/
        02-do-more-stuff/
        99-publish/
      00-import.qmd
      01-do-stuff.qmd
      02-do-more-stuff.qmd
      99-publish.qmd
      README.qmd

The naming here is arbitrary; qproj does not compel you to follow it.
To specify a custom rendering order, you can put a `_qproj.yml` file in the root of the workflow directory; see `proj_workflow_config()` for details.

There are some rules governing the use of subdirectories of `data/`:

-   Each `.qmd` file can write data to only one subdirectory: its *target* directory.

-   A `.qmd` file can use as *source* directories only subdirectories created earlier in the workflow.

There are two special files in the workflow: `00-import.qmd` and `99-publish.qmd`:

-   Use `00-import.qmd` to import data into the workflow from the "rest of the universe".

-   Use `99-publish.qmd` to manage the data that you wish to make available outside your workflow.

Using externally-accessible sites (e.g. Google Drive) from which to import data would make your workflow portable.
To run your workflow on other computers, you would have to ensure access (credentials, etc.) to the external sites.

The purpose here is to provide a simple way to manage the dependencies within a workflow.
As your project advances, you may need a more sophisticated approach; [targets](https://docs.ropensci.org/targets/) gives you much more control to specify the dependencies within your project.

#### Implementation

There's a set of functions to manage workflows:

-   `proj_use_workflow()`: creates a directory for a new workflow, including a `data` directory.
-   `use_qmd()`: creates a new Quarto file (from a template) in your workflow.

The function `proj_use_workflow()` has an argument `git_ignore_data`, which defaults to `FALSE`; this applies to the workflow's `data/` directory.
You will have to figure out the right answer for a given situation, or you may have to manage `.gitignore` file yourself if you want to manage with finer granularity.

There's another set of functions to manage directories from within a `.qmd` file.

-   `proj_create_dir_target()`: create the target directory.
-   `proj_path_source()`: function factory, creates function to access source paths.
-   `proj_path_target()`: function factory, creates function to access target paths.
-   `proj_dir_info()`: get concise version of data returned from `fs::dir_info()`.

The function `proj_create_dir_target()` has an argument `clean` which defaults to `TRUE`.
Its purpose is to indicate if an existing target directory is to be deleted before it is created.

There is one situation where it is useful to specify `clean` as `FALSE`.
Let's say that the external source used by your `00-import.qmd` file is a collection of daily files, with a new file added every day.
You may not wish to download *all* the files, every time the workflow is rendered.

The functions `proj_path_source()` and `proj_path_target()` are function factories; they return functions.
Within a `.qmd` file, you would use these returned functions to access paths in your source directories and your target directory.

For example:

``` {.r}
# path_source and path_target will be functions
path_source <- proj_path_source("01-do-stuff")
path_target <- proj_path_target("01-do-stuff")
```

These function factories each take a single argument, `name`, which shall correspond to the basename of the `.qmd` file that uses it.
The boilerplate code to support this is included in the template used with `use_qmd()`.

In the rest of your `.qmd` file, you can use `path_source()` and `path_target()` in a similar way as you use `here::here()`: they provide you with locally-valid fully-qualified paths to the workflow's `data/` directory.

`path_source()` validates that the path requested is **earlier** in the workflow than the `name` used in the function factory; `path_target()` uses the `name` to help form the path:

``` {.r}
# returns: "/path/to/this/workflow/00-import/raw-data.csv"
path_source("00-import", "raw-data.csv")

# throws error because this path is not earlier than "01-do-stuff"
path_source("02-do-more-stuff", "tidy-data.csv")

# returns: "/path/to/this/workflow/01-do-stuff/clean-data.csv"
path_target("clean-data.csv")
```

### DESCRIPTION file

For package development and deployment, the DESCRIPTION file is used to manage dependencies.
This idea is extended to analysis workflows: declare all the dependencies in a DESCRIPTION file.

This package uses `pak::pak()` to install dependencies.
The `Remotes` field can be used to specify GitHub and private repositories; the analysis developer will have to manage the `Remotes` field manually.

The purpose here is to provide a simple way to manage a project's package-dependencies.
As your project advances, you may need a more sophisticated approach; [renv](https://rstudio.github.io/renv/) gives you much more control to specify fixed versions of packages to use.

#### Implementation

-   `proj_create()`: creates a new project with a DESCRIPTION file.
-   `proj_check_deps()`, `proj_update_deps()`: checks (updates) dependencies listed in the DESCRIPTION file against those used in the project.
-   `proj_install_deps()`: installs the package-dependencies listed in the DESCRIPTION file via `pak`.

## Summary

This package is meant to help you make a first start with Quarto-based analysis workflows.
That said, there are wonderful comprehensive tools out there that support:

-   package dependencies, e.g. [renv](https://rstudio.github.io/renv/index.html).
-   workflow dependencies, e.g. [targets](https://docs.ropensci.org/targets/).
-   Quarto formats, e.g. the whole [Quarto](https://quarto.org/) ecosystem.

As you get a handle on a particular workflow, it may make sense to adopt one of these more-comprehensive tools; this represents success.
In the end, the goal of this package is to help you get your workflow off the ground quickly.
