#' Create project
#'
#' @description
#' Creates a new analysis project directory with a `DESCRIPTION` file,
#' `NAMESPACE`, `README.md`, and `.gitignore`.
#'
#' Provide an absolute `path`, or a relative `path` from your current
#' working-directory. The target directory must either not exist or be
#' empty; otherwise creation will abort to avoid overwriting files.
#'
#' Any named entries supplied via `fields` are written into
#' `DESCRIPTION`, allowing you to override defaults such as `Title`,
#' `Version`, or add custom fields.
#'
#' @param path `character` path to the new project directory.
#' @param fields `list` of additional fields to set in `DESCRIPTION`.
#' @param rstudio `logical` whether to also create a minimal `.Rproj` file
#'   so RStudio / Positron treat the directory as a project. Defaults to
#'   `TRUE`.
#'
#' @return Invisible `character` path to the created project, called for
#'   side effects.
#' @examples
#' # not run because it produces side effects
#' if (FALSE) {
#'   proj_create("../new-project-name")
#' }
#' @export
#'
proj_create <- function(path, fields = list(), rstudio = TRUE) {

  if (length(fields) > 0 && (is.null(names(fields)) || any(names(fields) == ""))) {
    cli::cli_abort("`fields` must be a named list.")
  }

  pkg_name <- basename(path)
  if (!is_valid_pkg_name(pkg_name)) {
    cli::cli_abort(c(
      "Project directory name {.val {pkg_name}} is not a valid R package name.",
      "i" = "Use only ASCII letters, digits, and dots; start with a letter; do not end with a dot.",
      "i" = "qproj reuses {.code DESCRIPTION} from R package conventions to manage dependencies."
    ))
  }

  if (fs::file_exists(path) && !fs::is_dir(path)) {
    cli::cli_abort("{.path {path}} already exists and is not a directory.")
  }

  if (fs::dir_exists(path)) {
    dir_contents <- fs::dir_ls(path, all = TRUE, type = "any")
    if (length(dir_contents) > 0) {
      cli::cli_abort("{.path {path}} already exists and is not empty.")
    }
  } else {
    fs::dir_create(path)
  }

  desc_obj <- desc::description$new("!new")
  desc_obj$set("Package", pkg_name)
  desc_obj$set("Title", "Analysis Project")
  desc_obj$set("Version", "0.1.0")

  if (length(fields) > 0) {
    for (field_name in names(fields)) {
      desc_obj$set(field_name, fields[[field_name]])
    }
  }

  desc_obj$write(file = fs::path(path, "DESCRIPTION"))

  writeLines("# Generated by roxygen2: do not edit by hand", fs::path(path, "NAMESPACE"))

  writeLines(c(
    paste0("# ", pkg_name),
    "",
    "An analysis project scaffolded by [qproj](https://github.com/rujinlong/qproj).",
    "",
    "## Quick start",
    "",
    "```r",
    'qproj::proj_use_workflow("analyses")',
    'qproj::use_qmd("01-import", path_proj = "analyses")',
    "```",
    "",
    "See `vignette(\"design-philosophy\", package = \"qproj\")` for the full layout."
  ), fs::path(path, "README.md"))

  writeLines(c(".Rproj.user", ".Rhistory", ".RData", ".Ruserdata"), fs::path(path, ".gitignore"))

  if (rstudio) {
    writeLines(c(
      "Version: 1.0",
      "",
      "RestoreWorkspace: Default",
      "SaveWorkspace: Default",
      "AlwaysSaveHistory: Default",
      "",
      "EnableCodeIndexing: Yes",
      "UseSpacesForTab: Yes",
      "NumSpacesForTab: 2",
      "Encoding: UTF-8",
      "",
      "RnwWeave: Sweave",
      "LaTeX: pdfLaTeX"
    ), fs::path(path, paste0(pkg_name, ".Rproj")))
  }

  cli::cli_alert_success("Created project at {.path {path}}")
  cli::cli_alert_info("Next: call {.fn proj_use_workflow} to set up an analyses directory.")

  invisible(path)
}

#' Set up workflow directory
#'
#' @description
#' Creates an `analyses/` directory (or custom path) with a `data/`
#' subdirectory, `.gitignore` rules, and a `README.md`.
#'
#' @param path_proj `character` path to the workflow directory,
#'   relative to the project directory. Defaults to `"analyses"`.
#' @param git_ignore_data `logical` indicates to add `data` directory
#'   contents to `.gitignore`.
#'
#' @return Invisible `NULL`, called for side effects.
#' @examples
#' # not run because it creates side effects
#' \dontrun{
#'   proj_use_workflow()
#' }
#' @export
#'
proj_use_workflow <- function(path_proj = "analyses", git_ignore_data = TRUE) {

  fs::dir_create(path_proj)

  data_dir <- fs::path(path_proj, "data")
  fs::dir_create(data_dir)

  # Tracked stub keeps data/ in git despite the gitignore rule below
  data_readme <- fs::path(data_dir, "README.md")
  if (!fs::file_exists(data_readme)) {
    writeLines(c("# Data Directory", "", "Data files in this folder are ignored by git."), data_readme)
  }

  if (git_ignore_data) {
    gitignore_path <- ".gitignore"
    ignores <- c(
      paste0(path_proj, "/data/*"),
      paste0(path_proj, "/tmp/"),
      paste0("!", path_proj, "/data/README.md")
    )
    # Append only new lines so repeated calls don't pile up duplicates
    existing <- if (fs::file_exists(gitignore_path)) readLines(gitignore_path) else character(0)
    new_lines <- ignores[!ignores %in% existing]
    if (length(new_lines) > 0) {
      if (length(existing) > 0) {
        cat("\n", file = gitignore_path, append = TRUE)
      }
      cat(paste0(new_lines, "\n"), sep = "", file = gitignore_path, append = TRUE)
    }
  }

  # Don't overwrite an existing user _quarto.yml
  quarto_yml_path <- fs::path(path_proj, "_quarto.yml")
  if (!fs::file_exists(quarto_yml_path)) {
    template_path <- system.file("templates", "_quarto.yml", package = "qproj")
    if (!nzchar(template_path)) {
      cli::cli_abort("Could not locate {.file _quarto.yml} template in the qproj package.")
    }
    fs::file_copy(template_path, quarto_yml_path)
  }

  readme_path <- fs::path(path_proj, "README.md")
  if (!fs::file_exists(readme_path)) {
    writeLines(c(
      paste0("# ", basename(path_proj)),
      "",
      "This directory contains the analysis workflow.",
      "",
      "## Structure",
      "",
      "- Each analysis file writes only to its own subdirectory of `data/`.",
      "- Files are named with a numeric prefix to indicate execution order,",
      "  e.g. `01-import.qmd`, `02-clean.qmd`, `99-summary.qmd`.",
      "  The `00-` prefix is reserved for the framework's `data/00-raw/`",
      "  input region -- start your own steps at `01-` or higher.",
      "",
      "## Usage",
      "",
      "Create a new analysis file:",
      "",
      "```r",
      'qproj::use_qmd("01-import")',
      "```"
    ), readme_path)
  }

  cli::cli_alert_success("Created workflow directory at {.path {path_proj}}")
  cli::cli_alert_info("Create analysis files with {.fn use_qmd}, e.g. {.code use_qmd(\"01-import\")}")

  invisible(NULL)
}
